### ISSUE TITLE
How to handle and detect an E/GeckoRemoteCodec: Callbacks is dead error

### ISSUE THREAD

**Issue by acrolink** [mozilla/geckoview#117]
Called by `gecko-dev/mobile/android/geckoview/src/main/java/org/mozilla/gecko/media/Codec.java`: 

```
    // IBinder.DeathRecipient
    @Override
    public synchronized void binderDied() {
        Log.e(LOGTAG, "Callbacks is dead");
        try {
            release();
        } catch (RemoteException e) {
            // Nowhere to report the error.
        }
    }
```
This error occurs sometimes when playing YouTube videos inside a `GeckoView` causing the `GeckoView` to freeze. My question, how to detect when this happens and trigger an action (e.g. a session reload) in such a case?

**Comment by snorp** [comment]
That would occur due to a crash in the decoding service. You might have some logcat indicating why it occurred. This would indicate a bug either in Gecko or the OS. The decoder process should definitely restart if it crashes, though, so I've filed a bug about that. You can followup here: https://bugzilla.mozilla.org/show_bug.cgi?id=1617894

**Comment by acrolink** [comment]
The preceding error message is:
`E/ACodec: [OMX.MS.VP9.Decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010`
